[[redirects]]
  from = "/obrien-watersports-b2c/obrien/wakesurfing/5637206843.c"
  to = "/collections/wakesurfing"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/wakesurfing/wakesurf-boards/5637206844.c"
  to = "/collections/wakesurf-boards"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/wakesurfing/surf-ropes/5637206845.c"
  to = "/collections/wakesurf-ropes"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/wakesurfing/wakesurf-accessories/5637206846.c"
  to = "/collections/wakesurf-accessories"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/wakeboarding/5637206847.c"
  to = "/collections/wakeboarding"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/wakeboarding/wakeboards/5637206848.c"
  to = "/collections/wakeboards"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/wakeboarding/wakeboard-bindings/5637206849.c"
  to = "collections/wakeboard-bindings"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/wakeboarding/wake-ropes/5637206850.c"
  to = "/collections/wakeboard-ropes"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/wakeboarding/wake-accessories/5637206851.c"
  to = "/collections/wakeboard-accessories"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/paddleboarding/5637206852.c"
  to = "/collections/stand-up-paddleboarding"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/paddleboarding/paddleboards/5637206853.c"
  to = "/collections/stand-up-paddleboards"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/paddleboarding/paddles/5637206854.c"
  to = "/collections/stand-up-paddleboard-paddles"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/paddleboarding/paddleboard-accessories/5637206855.c"
  to = "/collections/stand-up-paddleboard-accessories"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/waterskiing/5637206856.c"
  to = "/collections/water-skiing"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/waterskiing/waterskis/5637206857.c"
  to = "/collections/water-skis"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/waterskiing/ski-bindings/5637206858.c"
  to = "/collections/water-ski-bindings"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/waterskiing/ski-ropes/5637206859.c"
  to = "/collections/water-ski-ropes"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/waterskiing/ski-accessories/5637206860.c"
  to = "/collections/water-ski-accessories"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/kneeboarding/5637206861.c"
  to = "/collections/kneeboarding"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/kneeboarding/kneeboards/5637206862.c"
  to = "/collections/kneeboards"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/kneeboarding/kneeboard-ropes/5637206863.c"
  to = "/collections/kneeboard-ropes"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/tubing/5637206865.c"
  to = "/collections/tubing"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/tubing/towables/5637206866.c"
  to = "/collections/towable-tubes"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/tubing/tubing-ropes/5637206867.c"
  to = "/collections/tube-ropes"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/tubing/tube-accessories/5637206868.c"
  to = "/collections/tube-accessories"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/floating/5637206869.c"
  to = "/collections/floating"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/floating/party-floats/5637206870.c"
  to = "/collections/party-floats"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/floating/foam-floats/5637206871.c"
  to = "/collections/foam-floats"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/floating/pool-float/5637212080.c"
  to = "/collections/pool-floats"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/floating/float-accessories/5637206872.c"
  to = "/collections/float-accessories"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/ropes-handles/5637206873.c"
  to = "/collections/tow-ropes"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/ropes-handles/tow-ropes-handles/5637206874.c"
  to = "/collections/ropes-and-handles"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/ropes-handles/tube-ropes/5637206875.c"
  to = "/collections/tube-ropes"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/ropes-handles/rope-accessories/5637206876.c"
  to = "/collections/rope-accessories"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/life-jackets-vests/5637206877.c"
  to = "/collections/life-jackets-and-vests"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/life-jackets-vests/mens-life-jackets/5637206878.c"
  to = "/collections/mens-life-jackets-and-vests"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/life-jackets-vests/womens-life-jackets/5637206879.c"
  to = "/collections/womens-life-jackets-and-vests"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/life-jackets-vests/kids-life-jackets/5637206880.c"
  to = "/collections/kids-life-jackets-and-vests"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/life-jackets-vests/pet-vests/5637206883.c"
  to = "/collections/pet-life-jackets"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/life-jackets-vests/safety-equipment/5637206882.c"
  to = "/collections/boat-safety"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/extras/5637206884.c"
  to = "/collections/more-gear"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/extras/gloves/5637206885.c"
  to = "/collections/gloves"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/extras/bags/5637206886.c"
  to = "/collections/bags"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/extras/apparel/5637206887.c"
  to = "/collections/apparel"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/extras/merchandise/5637206888.c"
  to = "/collections/merchandise"

[[redirects]]
  from = "/obrien-watersports-b2c/obrien/extras/replacement-parts/5637206889.c"
  to = "/collections/replacement-parts"
